export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const USER_UPDATE_PROFILE_PICTURE_REQUEST = "USER_UPDATE_PROFILE_PICTURE_REQUEST";
export const USER_UPDATE_BACKGROUND_PICTURE_REQUEST = "USER_UPDATE_BACKGROUND_PICTURE_REQUEST";

export const USER_UPDATE_PROFILE_PICTURE_SUCCESS = "USER_UPDATE_PROFILE_PICTURE_SUCCESS";
export const USER_UPDATE_BACKGROUND_PICTURE_SUCCESS = "USER_UPDATE_BACKGROUND_PICTURE_SUCCESS";

export const USER_UPDATE_PROFILE_PICTURE_FAIL = "USER_UPDATE_PROFILE_PICTURE_FAIL";
export const USER_UPDATE_BACKGROUND_PICTURE_FAIL = "USER_UPDATE_BACKGROUND_PICTURE_FAIL";
 
 

 
